spring:
#  security:
#    user:
#      name: admin
#      password: admin
  application:
    name: springstudents
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students


    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/main-changelog.xml